[package]
name = "example-axum"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
slate = { path = "../..", features = ["axum"] }
rust-embed = "8"
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
serde_json = "1"
anyhow = "1"
tracing-subscriber = "0.3"
